### ISSUE TITLE
Using large datasets

### ISSUE THREAD

**Issue by miseminger** [STAT540-UBC/STAT540-UBC.github.io#24]
Has anyone got any tips on dealing with large datasets (>10GB) in R?  The expression data matrix we're hoping to work with is a 8GB (compressed) / 61GB (uncompressed) sparse matrix (.mtx) and my RStudio goes unresponsive at the very thought of it it seems like. :)

**Comment by kdkorthauer** [comment]
Such a large and sparse expression matrix sounds like you're dealing with single-cell RNA-seq data for many many samples - is this right? I can recommend a couple of things (general comments followed by specific implementations for certain data formats):

- For the sparsity, you'll want to read into an object that is specialized to handle sparse matrices - for example, only stores the non-zero counts and their locations, rather than also storing all the zeroes. Check out the `dgCMatrix` class from the `Matrix` package. 
  - If this is single cell expression data, the `SingleCellExperiment` class/package (basically an extension of `SummarizedExperiment` specifically for single cell data) accommodates the `dgCMatrix` class
  - Further, if it's 10X data specifically, check out the function `read10xCounts()` in the `DropletUtils` package which creates a `SingleCellExperiment` object from CellRanger output
- For the size, you can also look at out of memory ways to handle the data, such as HDF5 files - these are a special file format with which R can efficiently interact with subsetting operations to allow exploring/analyzing the data in chunks without needing to read the whole thing into memory
  - [Here's a page](http://biocworkshops2019.bioconductor.org.s3-website-us-east-1.amazonaws.com/page/bioc2019singlecell__bioc2019singlecell/) that shows this in action for 10X single cell data, but this assumes the HDF5 file is already created. If it isn't already available in that form, it's a little trickier, but you can create it yourself - see [here](https://rdrr.io/github/MarioniLab/DropletUtils/man/write10xCounts.html) (but you might need to be able to read it in memory first, I'm not sure - if so, the sparse representation in the previous point will be helpful!)

**Comment by kdkorthauer** [comment]
Also, please try to post these questions to the Discussion repo. This repo is for creating the course website. Thanks!
